language: java
jdk:
  - oraclejdk10
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
deploy:
  provider: script
  script: "./gradlew bintrayUpload"
  skip_cleanup: true
  on:
    tags: true
install:
  - ./gradlew clean build