language: java
jdk:
  - oraclejdk10
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && ./gradlew publish"
  skip_cleanup: true
  on:
    all_branches: true
#    tags: true
install:
  - ./gradlew clean build